allow-other: false
logging:
    type: syslog
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
file_cache:
    path: /mnt/cache
    timeout-sec: 120
azstorage:
    account-name: xiaoliuinterns # TO BE FILLED
    endpoint: https://xiaoliuinterns.blob.core.windows.net/   # TO BE FILLED
    container: kailai-yang  # TO BE FILLED
    mode: sas
    sas: ?sv=2023-01-03&st=2025-03-06T03%3A13%3A35Z&se=2025-03-13T03%3A13%3A00Z&skoid=568e5914-ecc1-47fe-b4a8-4007497b49e5&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-03-06T03%3A13%3A35Z&ske=2025-03-13T03%3A13%3A00Z&sks=b&skv=2023-01-03&sr=c&sp=racwdxltf&sig=lus2CBQaUyU0EWF35IbxkvcKgBezWCFhHg7%2FX1MhLrQ%3D
    update-md5: false
    validate-md5: false
    virtual-directory: true
    max-results-for-list: 0
    disable-compression: false
    telemetry: ""
    honour-acl: false
components:
    - libfuse
    - file_cache
    - azstorage